"""
File-backed session store.

Owns:
    * locating the session file on disk
    * atomic writes (write to ``.tmp`` + ``os.replace``)
    * Netscape-format temp cookie file (used by yt-dlp), via a
      context manager that **always** removes the file on exit —
      this fixes the ``/tmp/ig_cookies_*.txt`` leak in legacy
      ``downloader._create_cookie_file_from_session``.

Encryption hooks are intentionally minimal: the v3 contract says
"sessions are sensitive; the store decides how to protect them".
A no-op default is provided so the store works on every platform;
operators who need encryption can subclass and override
:meth:`_serialize` / :meth:`_deserialize`.
"""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from types import TracebackType
from typing import Any, Iterable, Mapping, Optional, Type

from instaharvest._v3.config.output import OutputConfig
from instaharvest._v3.core.exceptions import SessionNotFoundError
from instaharvest._v3.core.protocols import Logger


class _NetscapeTempCookieFile:
    """Auto-deleted Netscape-format cookie file.

    Use only via context manager — the file is unlinked on ``__exit__``,
    even if an exception propagates.
    """

    def __init__(self, cookies: Iterable[Mapping[str, Any]], logger: Logger) -> None:
        self._cookies = list(cookies)
        self._logger = logger
        self.path: str = ""

    def __enter__(self) -> "_NetscapeTempCookieFile":
        fd, path = tempfile.mkstemp(prefix="ig_cookies_", suffix=".txt")
        self.path = path
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write("# Netscape HTTP Cookie File\n")
                fh.write("# Generated by instaharvest; auto-deleted on close\n\n")
                for cookie in self._cookies:
                    domain = cookie.get("domain", ".instagram.com")
                    domain_flag = "TRUE" if str(domain).startswith(".") else "FALSE"
                    cookie_path = cookie.get("path", "/")
                    secure = "TRUE" if cookie.get("secure", True) else "FALSE"
                    expires = int(cookie.get("expires", 0))
                    name = cookie.get("name", "")
                    value = cookie.get("value", "")
                    if not name:
                        continue
                    fh.write(
                        f"{domain}\t{domain_flag}\t{cookie_path}\t"
                        f"{secure}\t{expires}\t{name}\t{value}\n"
                    )
        except Exception:
            self._safe_unlink()
            raise
        return self

    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        tb: Optional[TracebackType],
    ) -> None:
        self._safe_unlink()

    def _safe_unlink(self) -> None:
        if not self.path:
            return
        try:
            os.unlink(self.path)
        except FileNotFoundError:
            pass
        except OSError as exc:
            self._logger.warning("failed to unlink temp cookie file", path=self.path, error=str(exc))
        finally:
            self.path = ""


class FileSessionStore:
    """Concrete ``SessionStore`` reading/writing a JSON session file."""

    def __init__(self, config: OutputConfig, logger: Logger) -> None:
        self._dir: Path = Path(config.session_dir)
        self._filename: str = config.session_filename
        self._logger = logger

    @property
    def path(self) -> Path:
        return self._dir / self._filename

    # SessionStore protocol -----------------------------------------------

    def exists(self) -> bool:
        return self.path.is_file()

    def load(self) -> Mapping[str, Any]:
        if not self.exists():
            raise SessionNotFoundError(str(self.path))
        return self._deserialize(self.path.read_bytes())

    def save(self, data: Mapping[str, Any]) -> None:
        self._dir.mkdir(parents=True, exist_ok=True)
        payload = self._serialize(data)
        tmp = self.path.with_suffix(self.path.suffix + ".tmp")
        tmp.write_bytes(payload)
        os.replace(tmp, self.path)
        self._logger.info("session saved", path=str(self.path))

    def temp_cookie_file(self) -> _NetscapeTempCookieFile:
        cookies = self.load().get("cookies", [])
        return _NetscapeTempCookieFile(cookies, self._logger)

    # Hooks for subclasses ------------------------------------------------

    def _serialize(self, data: Mapping[str, Any]) -> bytes:
        return json.dumps(dict(data), indent=2, ensure_ascii=False).encode("utf-8")

    def _deserialize(self, payload: bytes) -> Mapping[str, Any]:
        return json.loads(payload.decode("utf-8"))
